// Code generated by "stringer -type=StyleType"; DO NOT EDIT.

package linkedinfmt

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StyleNone-0]
	_ = x[StyleBold-1]
	_ = x[StyleItalic-2]
	_ = x[StyleLineBreak-3]
	_ = x[StyleList-4]
	_ = x[StyleListItem-5]
	_ = x[StyleParagraph-6]
	_ = x[StyleSubscript-7]
	_ = x[StyleSuperscript-8]
	_ = x[StyleHyperlink-9]
	_ = x[StyleUnderline-10]
}

const _StyleType_name = "StyleNoneStyleBoldStyleItalicStyleLineBreakStyleListStyleListItemStyleParagraphStyleSubscriptStyleSuperscriptStyleHyperlinkStyleUnderline"

var _StyleType_index = [...]uint8{0, 9, 18, 29, 43, 52, 65, 79, 93, 109, 123, 137}

func (i StyleType) String() string {
	if i < 0 || i >= StyleType(len(_StyleType_index)-1) {
		return "StyleType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _StyleType_name[_StyleType_index[i]:_StyleType_index[i+1]]
}
